name: shikon_voteapp
description: "A flutter project that provides voting service on the Shikon Fes."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  shared_preferences: ^2.1.1
  mobile_scanner: any
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  fl_chart: ^0.70.2
  collection: ^1.19.1
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  flutter_charts: ^0.5.2
  firebase_database: any
  connectivity_plus: ^6.1.3
  firebase_data_connect: ^0.1.0
  excel: ^2.1.0
  csv: ^5.0.2
  share_plus: ^7.1.0
  google_sign_in: any
  flutter_facebook_auth: any
  twitter_login: any
  camera: ^0.10.5+4
  path_provider: ^2.1.1



flutter:
  uses-material-design: true
  fonts:
  - family: IBM Plex Sans JP
    fonts:
      - asset: assets/IBMPlexSansJP-Thin.ttf
        weight: 100
      - asset: assets/IBMPlexSansJP-ExtraLight.ttf
        weight: 200
      - asset: assets/IBMPlexSansJP-Light.ttf
        weight: 300
      - asset: assets/IBMPlexSansJP-Regular.ttf
        weight: 400
      - asset: assets/IBMPlexSansJP-Medium.ttf
        weight: 500
      - asset: assets/IBMPlexSansJP-SemiBold.ttf
        weight: 600
      - asset: assets/IBMPlexSansJP-Bold.ttf
        weight: 700
  - family: A-OTF-UDShinGoPr6N
    fonts:
      - asset: assets/A-OTF-UDShinGoPr6N-Light.otf
        weight: 300
      - asset: assets/A-OTF-UDShinGoPr6N-Regular.otf
        weight: 400
      - asset: assets/A-OTF-UDShinGoPr6N-Medium.otf
        weight: 500
      - asset: assets/A-OTF-UDShinGoPr6N-DeBold.otf
        weight: 600
      - asset: assets/A-OTF-UDShinGoPr6N-Bold.otf
        weight: 700
        
  assets:
  #ステージ団体
    - assets/Stage/
    - assets/Stage/Stage01.jpg
    - assets/Stage/Stage02.jpg
    - assets/Stage/Stage03.jpg
    - assets/Stage/Stage04.jpg
    - assets/Stage/Stage05.jpg
    - assets/Stage/Stage06.jpg
    - assets/Stage/Stage07.jpg
    - assets/Stage/Stage08.jpg
    - assets/Stage/Stage09.jpg
    - assets/Stage/Band01.jpg
    - assets/Stage/Band02.jpg
    - assets/Stage/Band03.jpg
    - assets/Stage/Band04.jpg
    - assets/Stage/Band05.jpg
    - assets/Stage/Band06.jpg
    - assets/Stage/Performance01.jpg
    - assets/Stage/Performance02.jpg
    - assets/Stage/Performance03.jpg
    - assets/Stage/Performance04.jpg
    - assets/Stage/Performance05.jpg
    - assets/Stage/No Select.jpg
    - assets/Stage/Roten_a.jpg
    - assets/Stage/Roten_b.jpg
    - assets/Stage/Roten_c.jpg
    - assets/Stage/Roten_d.jpg
    - assets/Stage/Roten_e.jpg
    - assets/Stage/Roten_f.jpg
    - assets/Stage/Roten_g.jpg
    - assets/Stage/Roten_h.jpg
  #1階
    - assets/First/
    - assets/First/S101.jpg
    - assets/First/S102.jpg
    - assets/First/S103.jpg
    - assets/First/S104.jpg
    - assets/First/S105.jpg
    - assets/First/N101.jpg
    - assets/First/N102.jpg
    - assets/First/N103.jpg
    - assets/First/N104.jpg
    - assets/First/N105.jpg
    - assets/First/T101.jpg
    - assets/First/T102.jpg
    - assets/First/Music_Room.jpg
    - assets/First/Technology_Room.jpg
    - assets/First/Art_Room_1.jpg
    - assets/First/Art_Room_2.jpg
    - assets/First/Hifuku_Room.jpg
    - assets/First/Chori_Room.jpg
  #2階
    - assets/Second/
    - assets/Second/S201.jpg
    - assets/Second/S202.jpg
    - assets/Second/S203.jpg
    - assets/Second/S204.jpg
    - assets/Second/S205.jpg
    - assets/Second/S206.jpg
    - assets/Second/S207.jpg
    - assets/Second/N201.jpg
    - assets/Second/N202.jpg
    - assets/Second/N203.jpg
    - assets/Second/N204.jpg
    - assets/Second/N205.jpg 
    - assets/Second/T201.jpg
    - assets/Second/T202.jpg
    - assets/Second/Computer_Room_1.jpg
    - assets/Second/Computer_Room_2.jpg
    - assets/Second/CALL_1.jpg
    - assets/Second/CALL_2.jpg
    - assets/Second/lib.jpg
  #3階
    - assets/Third/
    - assets/Third/S301.jpg
    - assets/Third/S302.jpg
    - assets/Third/S303.jpg
    - assets/Third/S304.jpg
    - assets/Third/S305.jpg
    - assets/Third/S306.jpg
    - assets/Third/S307.jpg
    - assets/Third/N301.jpg
    - assets/Third/N302.jpg
    - assets/Third/N303.jpg
    - assets/Third/N304.jpg
    - assets/Third/N305.jpg
    - assets/Third/N306.jpg
    - assets/Third/N307.jpg
    - assets/Third/T301.jpg
    - assets/Third/T302.jpg
    - assets/Third/T303.jpg
    - assets/Third/T304.jpg
    - assets/Third/T305.jpg
    - assets/Third/T306.jpg
    - assets/Third/T307.jpg
    - assets/Third/T308.jpg
    - assets/Third/Tokusho_1_2_3.jpg
    - assets/Third/Tokusho_4_5.jpg
    - assets/Third/Seibutsu_Experiment.jpg
    - assets/Third/Kyotsu_Experiment.jpg
    - assets/Third/Kagaku_Experiment.jpg
    - assets/Third/Butsuri_Experiment.jpg
    - assets/Third/Saho.jpg
    - assets/Third/Daikaigi.jpg